### ISSUE TITLE
expand_external support in nx.copy

### ISSUE THREAD

**Issue by toqduj** [nexusformat/python-nxs#13]
Hello developers, 

For Reasons of standards adherence, I need to transcode NeXus-to-NeXus. In a previous version of my code, I did this using the h5py library directly. However, I suspect that by using nexusformat's API, I can reduce my code and improve NeXus compatibility. So far, things are moving along well. 

For copying a group from the old file to the new structure, I use h5py.copy (http://docs.h5py.org/en/stable/high/group.html). This allows me to automatically include data from external links into the new file, so I can do away with the old file's dependencies. This appears not to be supported by nexusformat (yet). 

Would it be possible to include this functionality using a flag in the nexusformat copy method?

**Comment by rayosborn** [comment]
External links are supported in the separate [nexusformat](https://github.com/nexpy/nexusformat) package, which is under active development and documented as part of [NeXpy](http://nexpy.github.io/nexpy/). It was originally a fork of this `python-nxs` package, which is only minimally maintained but hasn't been removed completely, because NeXpy doesn't support NeXus files written in HDF4 or XML.

**Comment by toqduj** [comment]
Ok, let me copy this issue to the nexusformat issue page then... I didn't see the expand_external option in its copy functionality...
